---
title: Numpy入门
date: 2017-04-17 10:10:00
mathjax: true
categories: "Python第三方库"
tags:
    - Numpy
---

# N维数组对象ndarray

## ndarray对象的属性

属性 | 说明
:---:|:---:
.ndim | 维度的数量
.shape | ndarray对象的尺度，对于矩阵，n行m列
.size | ndarray对象元素的个数，相当于.shape中n\*m的值
.dtype | ndarray对象的元素类型
.itemsize | ndarray对象中每个元素的大小，以字节为单位

In [8]:
import numpy as np

a = np.array([ [1, 2, 3], [4, 5, 6] ] )
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)

[[1 2 3]
 [4 5 6]]
2 (2, 3) 6 int32 4


## 元素类型

数据类型 | 说明
:---:|:---:
bool | 布尔类型，True或False
intc | 与C语言中的int类型一致，一般是int32或int64
intp | 用于索引的整数，与C语言中ssize_t一致，int32或int64
int8 | 字节长度的整数，取值：[‐128, 127]
int16 | 16位长度的整数，取值：[‐32768, 32767]
int32 | 32位长度的整数，取值：[‐2 31 , 2 31 ‐1]
int64 | 64位长度的整数，取值：[‐2 63 , 2 63 ‐1]
uint8 | 8位无符号整数，取值：[0, 255]
uint16 | 16位无符号整数，取值：[0, 65535]
uint32 | 32位无符号整数，取值：[0, 2 32 ‐1]
uint64 | 32位无符号整数，取值：[0, 2 64 ‐1]
float16 | 16位半精度浮点数：1位符号位，5位指数，10位尾数，**(符号)尾数 \\(*10^{指数}\\)**
float32 | 32位半精度浮点数：1位符号位，8位指数，23位尾数
float64 | 64位半精度浮点数：1位符号位，11位指数，52位尾数
complex64 | 复数类型，实部和虚部都是32位浮点数
complex128 | 复数类型，实部和虚部都是64位浮点数

**ndarray为什么要支持这么多种元素类型？**  

- 科学计算涉及数据较多，对**存储和性能**都有较高要求
- 对元素类型精细定义，有助于NumPy**合理使用存储空间并优化性能**
- 对元素类型精细定义，有助于程序员对程序规模进行**合理评估**

# ndarray的创建

## 通过列表、元组等创建

In [13]:
a = np.array([1, 2, 3])
# 列表和元组可以共同使用，只需要元素个数相同
b = np.array([ [1, 2], (3, 4) ])
c = np.array([20, 21], dtype = np.float)
print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)

[1 2 3] int32
[[1 2]
 [3 4]] int32
[ 20.  21.] float64


当np.array()不指定dtype时，NumPy将根据数据情况关联一个dtype类型。

## 通过NumPy函数创建

函数 | 说明
:---:|:---:
np.arange(n) | 类似range()函数，返回ndarray类型，元素从0到n‐1
np.ones(shape) | 根据shape生成一个全1数组，shape是元组类型
np.zeros(shape) | 根据shape生成一个全0数组，shape是元组类型
np.full(shape,val) | 根据shape生成一个数组，每个元素值都是val
np.eye(n) | 创建一个正方的n*n单位矩阵，对角线为1，其余为0

In [14]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
a = np.ones((2, 3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [17]:
a = np.zeros((2, 3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
a = np.full((2, 3), 21, dtype = np.float)
print(a)

[[ 21.  21.  21.]
 [ 21.  21.  21.]]


In [22]:
a = np.eye(4)
print(a)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


函数 | 说明
:---:|:---:
np.linspace(start, end, n) | 根据起止数据等间距地填充数据，形成长度为n的数组
np.concatenate((a, b)) | 将两个或多个数组合并成一个新的数组

In [41]:
# 每个元素之间的间距为(end-start)/(n-1)
a = np.linspace(1, 10, 4)
print(a)

[  1.   4.   7.  10.]


In [91]:
# endpoint为False时，表示end不在最后生成的数组中
# 每个元素之间的间距为(end-start)/n
b = np.linspace(1, 10, 4, endpoint = False)
print(b)

[ 1.    3.25  5.5   7.75]


In [43]:
c = np.concatenate((a, b))
print(c)

[  1.     4.     7.    10.     1.     2.75   4.5    6.25]


函数 | 说明
:---:|:---:
np.ones_like(a) | 根据数组a的形状生成一个全1数组
np.zeros_like(a) | 根据数组a的形状生成一个全0数组
np.full_like(a,val) | 根据数组a的形状生成一个数组，每个元素值都是val

In [29]:
a = np.ones((4, 4))
print(a.shape)

(4, 4)


In [26]:
b = np.ones_like(a)
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [27]:
b = np.zeros_like(a)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [28]:
b = np.full_like(a, 6)
print(b)

[[ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]]


# ndarray数组的变换

## 维度变换

方法 | 说明
:---:|:---:
.reshape(shape) | 不改变数组元素，返回一个shape形状的数组，**原数组不变**
.resize(shape) | 与.reshape()功能一致，但**修改原数组**
.swapaxes(ax1,ax2) | 将数组n个维度中两个维度进行调换
.flatten() | 对数组进行降维，返回折叠后的一维数组，原数组不变

In [65]:
# 三维数组，为层*行*列
a = np.array([ 
                [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
                [[4, 4, 4, 4], [5, 5, 5, 5], [6, 6, 6, 6]] 
             ], dtype = np.int32)
print(a)

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [66]:
b = a.reshape((3, 8))
print(b)
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]
[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [78]:
# 修改原数组
a.resize((3, 8))
print(a)
a.shape = (4, 6)
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]
[[1 1 1 1 2 2]
 [2 2 3 3 3 3]
 [4 4 4 4 5 5]
 [5 5 6 6 6 6]]


In [68]:
b = a.flatten()
print(b)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


## 元素类型变换

In [72]:
print(a.dtype)

int32


In [70]:
# astype()方法一定会创建新的数组（原始数据的一个拷贝），即使两个类型一致
b = a.astype(np.float)
print(b)
print(b.dtype)

[[ 1.  1.  1.  1.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  6.  6.  6.  6.]]
float64


## 向列表的转换

In [73]:
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]


In [75]:
print(a.tolist())
print(type(a))

[[1, 1, 1, 1, 2, 2, 2, 2], [3, 3, 3, 3, 4, 4, 4, 4], [5, 5, 5, 5, 6, 6, 6, 6]]
<class 'numpy.ndarray'>


# ndarray数组的索引与切片

- 索引  
获取数组中**特定位置**元素的过程
- 切片  
获取数组元素**子集**的过程

## 一维数组

In [116]:
a = np.linspace(0, 51, 18)
print(a)

[  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.  30.  33.  36.  39.  42.
  45.  48.  51.]


In [117]:
print(a[2])
print(a[-2])

6.0
48.0


In [118]:
# 起始编号:终止编号(不含):步长
print(a[0:6:2])
print(a[10:2:-2])
print(a[::3])

[  0.   6.  12.]
[ 30.  24.  18.  12.]
[  0.   9.  18.  27.  36.  45.]


## 多维数组

In [120]:
a = np.arange(24).reshape((2, 3, 4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [109]:
print(a[1, 2, 3])
print(a[-2, 2, -3])

23
9


In [110]:
print(a[:, 1, 3])

[ 7 19]


In [113]:
print(a[:, 1:3, 3])

[[ 7 11]
 [19 23]]


In [114]:
print(a[:, 1:3, :])

[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [121]:
print(a[:, :, ::2])

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


# ndarray数组的运算

In [ ]:
%timeit a.argmax()

In [ ]:
import numpy as np

a = np.random.random((3, 5))
print(a)

a.argmax()