---
title: Python-模块-NumPy-ndarry对象
date: 2017-04-17 19:27:00
mathjax: true
categories: "Python-模块"
---

# N维数组对象ndarray

## ndarray对象的属性

属性 | 说明
:---:|:---:
.ndim | 维度的数量
.shape | ndarray对象的尺度，对于矩阵，n行m列
.size | ndarray对象元素的个数，相当于.shape中n\*m的值
.dtype | ndarray对象的元素类型
.itemsize | ndarray对象中每个元素的大小，以字节为单位

In [1]:
import numpy as np
 
a = np.array([ [1, 2, 3], [4, 5, 6] ] )
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)

[[1 2 3]
 [4 5 6]]
2 (2, 3) 6 int32 4


## 元素类型

数据类型 | 说明
:---:|:---:
bool | 布尔类型，True或False
intc | 与C语言中的int类型一致，一般是int32或int64
intp | 用于索引的整数，与C语言中ssize_t一致，int32或int64
int8 | 字节长度的整数，取值：[‐128, 127]
int16 | 16位长度的整数，取值：[‐32768, 32767]
int32 | 32位长度的整数，取值：[‐2 31 , 2 31 ‐1]
int64 | 64位长度的整数，取值：[‐2 63 , 2 63 ‐1]
uint8 | 8位无符号整数，取值：[0, 255]
uint16 | 16位无符号整数，取值：[0, 65535]
uint32 | 32位无符号整数，取值：[0, 2 32 ‐1]
uint64 | 32位无符号整数，取值：[0, 2 64 ‐1]
float16 | 16位半精度浮点数：1位符号位，5位指数，10位尾数，**(符号)尾数 \\(*10^{指数}\\)**
float32 | 32位半精度浮点数：1位符号位，8位指数，23位尾数
float64 | 64位半精度浮点数：1位符号位，11位指数，52位尾数
complex64 | 复数类型，实部和虚部都是32位浮点数
complex128 | 复数类型，实部和虚部都是64位浮点数

**ndarray为什么要支持这么多种元素类型？**  

- 科学计算涉及数据较多，对**存储和性能**都有较高要求
- 对元素类型精细定义，有助于NumPy**合理使用存储空间并优化性能**
- 对元素类型精细定义，有助于程序员对程序规模进行**合理评估**

# ndarray的创建

## 通过列表、元组等创建

In [13]:
a = np.array([1, 2, 3])
# 列表和元组可以共同使用，只需要元素个数相同
b = np.array([ [1, 2], (3, 4) ])
c = np.array([20, 21], dtype = np.float)
print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)

[1 2 3] int32
[[1 2]
 [3 4]] int32
[ 20.  21.] float64


当np.array()不指定dtype时，NumPy将根据数据情况关联一个dtype类型。

## 通过NumPy函数创建

函数 | 说明
:---:|:---:
np.arange(n) | 类似range()函数，返回ndarray类型，元素从0到n‐1
np.ones(shape) | 根据shape生成一个全1数组，shape是元组类型
np.zeros(shape) | 根据shape生成一个全0数组，shape是元组类型
np.full(shape,val) | 根据shape生成一个数组，每个元素值都是val
np.eye(n) | 创建一个正方的n*n单位矩阵，对角线为1，其余为0

In [14]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
a = np.ones((2, 3))
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [17]:
a = np.zeros((2, 3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
a = np.full((2, 3), 21, dtype = np.float)
print(a)

[[ 21.  21.  21.]
 [ 21.  21.  21.]]


In [22]:
a = np.eye(4)
print(a)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


函数 | 说明
:---:|:---:
np.linspace(start, end, n) | 根据起止数据等间距地填充数据，形成长度为n的数组
np.concatenate((a, b)) | 将两个或多个数组合并成一个新的数组

In [41]:
# 每个元素之间的间距为(end-start)/(n-1)
a = np.linspace(1, 10, 4)
print(a)

[  1.   4.   7.  10.]


In [91]:
# endpoint为False时，表示end不在最后生成的数组中
# 每个元素之间的间距为(end-start)/n
b = np.linspace(1, 10, 4, endpoint = False)
print(b)

[ 1.    3.25  5.5   7.75]


In [43]:
c = np.concatenate((a, b))
print(c)

[  1.     4.     7.    10.     1.     2.75   4.5    6.25]


函数 | 说明
:---:|:---:
np.ones_like(a) | 根据数组a的形状生成一个全1数组
np.zeros_like(a) | 根据数组a的形状生成一个全0数组
np.full_like(a,val) | 根据数组a的形状生成一个数组，每个元素值都是val

In [29]:
a = np.ones((4, 4))
print(a.shape)

(4, 4)


In [26]:
b = np.ones_like(a)
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [27]:
b = np.zeros_like(a)
print(b)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [28]:
b = np.full_like(a, 6)
print(b)

[[ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]
 [ 6.  6.  6.  6.]]


## 通过复制已有数组

In [75]:
a = np.arange(5)
b = a
c = a.view()
d = a.copy()

区别：

1. b = a  
b和a完全一样，改变b时a也跟着改变，是完全相同的对象
2. c = a.view()  
c是a的浅复制，c和a是不同的对象，但是改变c时a也跟着改变
3. d = a.copy()
d是a的深复制，改变d时a不改变。**推荐使用**。

# ndarray数组的变换

## 维度变换

方法 | 说明
:---:|:---:
.reshape(shape) | 不改变数组元素，返回一个shape形状的数组，**原数组不变**
.resize(shape) | 与.reshape()功能一致，但**修改原数组**
.swapaxes(ax1,ax2) | 将数组n个维度中两个维度进行调换
.flatten() .ravel() | 对数组进行降维，返回折叠后的一维数组，原数组不变
.T | 转置

In [46]:
# 三维数组，为层*行*列
a = np.array([ 
                [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
                [[4, 4, 4, 4], [5, 5, 5, 5], [6, 6, 6, 6]] 
             ], dtype = np.int32)
print(a)

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [47]:
b = a.reshape((3, 8))
print(b)
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]
[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]


In [48]:
# 修改原数组
a.resize((3, 8))
print(a)
a.shape = (4, 6)
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]
[[1 1 1 1 2 2]
 [2 2 3 3 3 3]
 [4 4 4 4 5 5]
 [5 5 6 6 6 6]]


In [68]:
b = a.flatten()
print(b)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [51]:
b = a.ravel()
print(b)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [53]:
b = a.T
print(b)

[[1 2 4 5]
 [1 2 4 5]
 [1 3 4 6]
 [1 3 4 6]
 [2 3 5 6]
 [2 3 5 6]]


## 元素类型变换

In [72]:
print(a.dtype)

int32


In [70]:
# astype()方法一定会创建新的数组（原始数据的一个拷贝），即使两个类型一致
b = a.astype(np.float)
print(b)
print(b.dtype)

[[ 1.  1.  1.  1.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  6.  6.  6.  6.]]
float64


## 向列表的转换

In [73]:
print(a)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6]]


In [75]:
print(a.tolist())
print(type(a))

[[1, 1, 1, 1, 2, 2, 2, 2], [3, 3, 3, 3, 4, 4, 4, 4], [5, 5, 5, 5, 6, 6, 6, 6]]
<class 'numpy.ndarray'>


# ndarray数组的索引与切片

- 索引  
获取数组中**特定位置**元素的过程
- 切片  
获取数组元素**子集**的过程

## 一维数组

In [3]:
import numpy as np
a = np.linspace(0, 51, 18)
print(a)

[  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.  30.  33.  36.  39.  42.
  45.  48.  51.]


In [117]:
# 使用特定的值
print(a[2])
print(a[-2])

6.0
48.0


In [118]:
# 使用切片
# 起始编号:终止编号(不含):步长
print(a[0:6:2])
print(a[10:2:-2])
print(a[::3])

[  0.   6.  12.]
[ 30.  24.  18.  12.]
[  0.   9.  18.  27.  36.  45.]


In [15]:
# 使用列表
print(a[[0, 3, 6]])
print(a[range(3)])

[  0.   9.  18.]
[ 0.  3.  6.]


## 多维数组

In [22]:
a = np.arange(24).reshape((2, 3, 4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
# 每个维度都使用特定的值
# 第一个维度为层向，第二个维度为行向
print(a[1, 2, 3])
print(a[-2, 2, -3])

23
9


In [110]:
# 使用切片
print(a[:, 1, 3])

[ 7 19]


In [113]:
print(a[:, 1:3, 3])

[[ 7 11]
 [19 23]]


In [114]:
print(a[:, 1:3, :])

[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [121]:
print(a[:, :, ::2])

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [42]:
# 使用列表
# 分别取a[1, 0, 0] a[0, 0, 2] a[1, 1, 3]的值
print(a[[1,0,1],[0,0,1],[0,2,3]])

[12  2 19]


In [43]:
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
# 找出每一列最大的值所在的索引
ind = data.argmax(axis=0)
print(ind)
# 根据索引找出最大的值
data_max = data[ind, range(data.shape[1])]
print (data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


# ndarray数组的运算

## NumPy一元函数

函数 | 说明
:---:|:---:
np.abs(x) np.fabs(x) | 计算数组各元素的绝对值
np.sqrt(x) | 计算数组各元素的平方根
np.square(x) | 计算数组各元素的平方
np.log(x) np.log10(x) np.log2(x) | 计算数组各元素以e为底、以10为底、以2为底的对数
np.ceil(x) np.floor(x) | 计算数组各元素的ceiling值 或 floor值
np.rint(x) | 计算数组各元素的四舍五入值
np.modf(x) | 将数组各元素的小数和整数部分以两个独立数组形式返回
np.cos(x) np.sin(x) np.tan(x) | 计算数组各元素的三角函数
np.exp(x) | 计算数组各元素的指数值
np.sign(x) | 计算数组各元素的符号值，1(+), 0, ‐1(‐)
np.sort(x) | 对数组进行排序
np.tile(x, (m, n)) | 将数组复制成(m,n)份


In [55]:
import numpy as np
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 0, -1).reshape(2, 2)
print(a)
print(b)

[[0 1]
 [2 3]]
[[4 3]
 [2 1]]


In [45]:
print(a/2)

[[ 0.   0.5]
 [ 1.   1.5]]


In [71]:
print(np.sort(b, axis = 0))

[[2 1]
 [4 3]]


In [73]:
print(np.tile(a, (2, 2)))

[[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]


## NumPy二元函数

函数 | 说明
:---:|:---:
+ ‐ \* / \*\* | 两个数组各元素进行对应运算
np.dot(x,y) | 矩阵相乘，即x.dot(y) 
np.maximum(x,y)  np.minimum(x,y) | 元素级的最大值/最小值计算
np.fmax(x,y)  np.fmin(x,y) | 同上
np.mod(x,y) | 元素级的模运算
np.copysign(x,y) | 将数组y中各元素值的符号赋值给数组x对应元素
>, <, >=, <=, ==, != | 算术比较，产生布尔型数组
np.vstack((a,b)) np.hstack((a,b)) | 数组拼接
np.hsplit(a,n) np.vsplit(a,n) | 将数组平均切成n份

In [45]:
import numpy as np
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 0, -1).reshape(2, 2)
print(a)
print(b)

[[0 1]
 [2 3]]
[[4 3]
 [2 1]]


In [57]:
print(a-b)
print(a-1)
print(b**2)

[[-4 -2]
 [ 0  2]]
[[-1  0]
 [ 1  2]]
[[16  9]
 [ 4  1]]


In [60]:
con = (b<2) | (b>3)
print(con)
print(b[con])

[[ True False]
 [False  True]]
[4 1]


In [62]:
matrix = np.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
con = (matrix[:,1] == 25)
print(con)
# 保留第2行
print(matrix[con, :])

[False  True False]
[[20 25 30]]


In [67]:
print(np.dot(a, b))

[[ 2  1]
 [14  9]]


In [60]:
print(np.maximum(a, b))
print(np.fmax(a, b))

[[4 3]
 [2 3]]
[[4 3]
 [2 3]]


In [41]:
print(np.mod(a, b))

[[0 1]
 [0 0]]


In [58]:
print(np.hstack((a, b)))
print(np.vstack((a, b)))

[[0 1 4 3]
 [2 3 2 1]]
[[0 1]
 [2 3]
 [4 3]
 [2 1]]


In [61]:
a = np.arange(24).reshape(2, 12)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [65]:
# 将a平均切割成4份
print(np.hsplit(a, 4))

[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3,  4,  5],
       [15, 16, 17]]), array([[ 6,  7,  8],
       [18, 19, 20]]), array([[ 9, 10, 11],
       [21, 22, 23]])]


In [64]:
# 在第2列和第5列之前分别切一刀
print(np.hsplit(a, (2, 5)))

[array([[ 0,  1],
       [12, 13]]), array([[ 2,  3,  4],
       [14, 15, 16]]), array([[ 5,  6,  7,  8,  9, 10, 11],
       [17, 18, 19, 20, 21, 22, 23]])]


## ndarray方法

方法 | 说明
:---:|:---:
.argsort() | 排序后的下标索引
.argmax() .argmin() | 最大值和最小值的下标索引

In [81]:
a = np.array([2, 5, 6, 2, 3])
print(a)
print(a.argmax())
print(a.argmin())
print(a.argsort())

[2 5 6 2 3]
2
0
[0 3 4 1 2]
