---
title: Python-模块-NumPy-常用函数
date: 2017-04-17 20:36:00
mathjax: true
categories: "Python-模块"
---

# 随机函数

函数 | 说明
:---:|:---:
rand(d0,d1,..,dn) | 根据d0‐dn创建随机数数组，浮点数，[0,1)，均匀分布
randn(d0,d1,..,dn) | 根据d0‐dn创建随机数数组，标准正态分布
randint(low[,high,shape]) | 根据shape创建随机整数或整数数组，范围是[low, high)
seed(s) | 随机数种子，s是给定的种子值

In [4]:
import numpy as np

a = np.random.rand(3, 4)
print(a)

[[ 0.19114922  0.7068554   0.97088057  0.22036382]
 [ 0.55174823  0.00680082  0.73785489  0.88970624]
 [ 0.45998671  0.13359651  0.83150316  0.19457805]]


In [8]:
b = np.random.randn(3, 4)
print(b)

[[ 1.12238235  0.27006584  0.63285753  1.08344082]
 [ 0.75890063 -0.41283425  1.20569367 -0.6684051 ]
 [-0.9419934   0.40069505 -0.78798551  1.60365521]]


In [9]:
c = np.random.randint(3, 10, (2, 3))
print(c)

[[6 5 7]
 [8 4 8]]


In [10]:
# 相同的种子，随机数的值相同
np.random.seed(10)
d = np.random.randint(3, 10, (2, 3))
print(d)

np.random.seed(10)
e = np.random.randint(3, 10, (2, 3))
print(e)

[[4 8 7]
 [3 4 6]]
[[4 8 7]
 [3 4 6]]


函数 | 说明
:---:|:---:
shuffle(a) | 根据数组a的第1轴进行随排列，改变数组a
permutation(a) | 根据数组a的第1轴产生一个新的乱序数组，不改变数组a
choice(a[,size,replace,p])| 从**一维数组**a中以概率p抽取元素，形成size形状新数组，replace表示是否可以重用元素，默认为False

In [20]:
# a改变
a = np.arange(18).reshape(6, 3)
print(a)
np.random.shuffle(a)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[15 16 17]
 [ 0  1  2]
 [ 3  4  5]
 [12 13 14]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
# a不改变
a = np.arange(18).reshape(6, 3)
print(a)
b = np.random.permutation(a)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2]
 [15 16 17]
 [ 6  7  8]
 [ 9 10 11]
 [ 3  4  5]
 [12 13 14]]


In [25]:
a = np.arange(18)
b = np.random.choice(a, (3, 4), True, p = a/np.sum(a))
print(b)

[[ 6 11 15 13]
 [ 7 16  6  9]
 [ 5  4 15  2]]


函数 | 说明
:---:|:---:
uniform(low,high,size) | 产生具有均匀分布的数组,low起始值,high结束值,size形状
normal(loc,scale,size) | 产生具有正态分布的数组,loc均值,scale标准差,size形状
poisson(lam,size) | 产生具有泊松分布的数组,lam随机事件发生率,size形状

# 统计函数

函数 | 说明
:---:|:---:
sum(a, axis=None) | 根据给定轴axis计算数组a相关元素之和，axis整数或元组
mean(a, axis=None) | 根据给定轴axis计算数组a相关元素的期望，axis整数或元组
average(a,axis=None,weights=None) | 根据给定轴axis计算数组a相关元素的加权平均值
std(a, axis=None) | 根据给定轴axis计算数组a相关元素的标准差
var(a, axis=None) | 根据给定轴axis计算数组a相关元素的方差

**axis=None是统计函数的标配参数**

In [26]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
print(np.sum(a, axis=0))

[15 18 21 24 27]


In [28]:
print(np.mean(a, axis=1))

[  2.   7.  12.]


In [31]:
# axis = 0为列向
# 以第2列为例
# (1*10+6*5+11*1)/(10+5+1) = 3.1875
print(np.average(a, axis = 0, weights = [10, 5, 1]))

[ 2.1875  3.1875  4.1875  5.1875  6.1875]


In [29]:
print(np.std(a), np.var(a))

4.32049379894 18.6666666667


函数 | 说明
:---:|:---:
min(a) max(a) | 计算数组a中元素的最小值、最大值
argmin(a) argmax(a) | 计算数组a中元素最小值、最大值的降一维后下标
unravel_index(index, shape) | 根据shape将一维下标index转换成多维下标
ptp(a) | 计算数组a中元素最大值与最小值的差
median(a) | 计算数组a中元素的中位数（中值）

In [32]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
print(np.max(a), np.min(a, axis = 0))

14 [0 1 2 3 4]


In [46]:
print(np.argmin(a, axis = 0), np.argmax(a, axis = 1), np.argmax(a))

[0 0 0 0 0] [4 4 4] 14


In [48]:
print(np.unravel_index([14], (3, 5)))

(array([2], dtype=int64), array([4], dtype=int64))


In [37]:
print(np.ptp(a))

14


In [38]:
print(np.median(a))

7.0


# 梯度函数

函数 | 说明
:---:|:---:
np.gradient(f) | 计算数组f中元素的梯度，当f为多维时，返回每个维度梯度

梯度：连续值之间的变化率，即斜率。  
XY坐标系中，连续三个X坐标对应的Y轴值为a、b、c，那么b的梯度是：(c‐a)/2  

对于[a, b, c, d]而言，  
a的梯度为：(b-a)/1  
b的梯度为：(c-a)/2  
c的梯度为：(d-b)/2  
d的梯度为：(d-c)/1  

In [51]:
a = np.random.randint(0, 20, (5))
print(a)

[11 10  9 15 18]


In [53]:
print(np.gradient(a))

[-1.  -1.   2.5  4.5  3. ]


In [54]:
a = np.random.randint(0, 20, (3, 5))
print(a)

[[16  7 11 17 14]
 [ 7 11  1  0 12]
 [ 5  4  7 18 12]]


In [56]:
# 结果分别表示，第0维的梯度和第1维的梯度
print(np.gradient(a))

[array([[ -9. ,   4. , -10. , -17. ,  -2. ],
       [ -5.5,  -1.5,  -2. ,   0.5,  -1. ],
       [ -2. ,  -7. ,   6. ,  18. ,   0. ]]), array([[ -9. ,  -2.5,   5. ,   1.5,  -3. ],
       [  4. ,  -3. ,  -5.5,   5.5,  12. ],
       [ -1. ,   1. ,   7. ,   2.5,  -6. ]])]
